- got user name and URL avatar from Twitter profile
Vladyslav225/JS_web-extention pull request #10
Opened 2023-04-21 16:44 UTC by Vladyslav225

For to receive user name created two function, because the selector of the parent element is different for the mobile and desktop versions. For to receive URL avatar user one function, because the selector of the parent element are the same.

2023-04-21 19:27 UTC, lebeichuk reviewed
будь-ласка зарефакторь весь файл scripts.js
поділи його на 2-3 файли по сенсу і структурі
бо читати таку простиню з довгими іменами всього **дуже** важко
дякую

2023-04-21 19:29 UTC, lebeichuk commented on web_extention/script.js
> +        getUserNameTwitterProfileDesktopVersion((userName) => {
плюс занадто довгі назви змінних і не тільки тут (всюди по файлу)
це фізично важко читати і сприймати

2023-04-21 19:30 UTC, lebeichuk requested changes

2023-04-21 19:30 UTC, lebeichuk commented on web_extention/script.js
> +        getUserNameTwitterProfileDesktopVersion((userName) => {
плюс занадто довгі назви змінних і функцій,  не тільки тут (всюди по файлу)
це фізично важко читати і сприймати

2023-04-21 19:47 UTC, Vladyslav225 commented on web_extention/script.js
> +        getUserNameTwitterProfileDesktopVersion((userName) => {
Хотів зробити рефактор після Facebook

2023-04-21 19:53 UTC, lebeichuk commented on web_extention/script.js
> +        getUserNameTwitterProfileDesktopVersion((userName) => {
не треба чекати
бо важко уже зараз

після Facebook простися тільки виросте

2023-04-21 19:53 UTC, Vladyslav225 commented on web_extention/script.js
> +        getUserNameTwitterProfileDesktopVersion((userName) => {
Добре
Зроблю

2023-04-25 08:49 UTC, Vladyslav225 commented
Need to refactor;
Check and correct publisher ID in the App-store.

2023-04-25 08:49 UTC, closed without merging