Pev 192: Got user name and URL avatar from Twitter profile; Refactor; Fixed
Vladyslav225/JS_web-extention pull request #11
Opened 2023-04-26 11:29 UTC by Vladyslav225

Got user name and URL avatar from Twitter profile:
    For to receive user name created two function, because the selector of the parent element is different for the mobile and desktop versions;
    For to receive URL avatar user one function, because the selector of the parent element are the same.

Refactor:
    Created file with URLs for parsing - created three global object-dictionaries:
        desktop version URLs;
        mobile version URLs;
        URLs for all version site - links that do not change for mobile and desktop versions of the site.
    Conditions for comparing links for different versions of the site.
    Created a function to explore the link in different versions of the site.

Fixed functions for the Google Play and the App Store:
    Received the publisher identifier in the form of a link to their page, rather than in the form of a name.

2023-04-26 11:49 UTC, lebeichuk commented on web_extention/analysisURLs.js
> +    const elementAccountName = document.querySelector('a.x1i10hfl.xjqpnuy.xa49m3k.xqeqjp1.x2hbi6w.xdl72j9.x2lah0s.xe8uvvx.xdj266r.x11i5rnm.xat24cr.x1mh8g0r.x2lwn1j.xeuugli.x1hl2dhg.xggy1nq.x1ja2u2z.x
can we somehow reduce this line?

2023-04-26 12:03 UTC, Vladyslav225 commented on web_extention/analysisURLs.js
> +    const elementAccountName = document.querySelector('a.x1i10hfl.xjqpnuy.xa49m3k.xqeqjp1.x2hbi6w.xdl72j9.x2lah0s.xe8uvvx.xdj266r.x11i5rnm.xat24cr.x1mh8g0r.x2lwn1j.xeuugli.x1hl2dhg.xggy1nq.x1ja2u2z.x
May be yes
I will try to get the parent element

2023-04-27 08:43 UTC, lebeichuk requested changes

2023-04-27 08:43 UTC, lebeichuk commented on web_extention/analysisURLs.js
> +function getYouTubeChanelId(callback) {
оце все було б логічно розділити на окремі файли
- publisher
- display name
- avatar

2023-04-27 09:12 UTC, Vladyslav225 commented on web_extention/analysisURLs.js
> +function getYouTubeChanelId(callback) {
В кожному цьому файлі визначення посилання та порівняння визначеного посилання з відкритим в браузері?

2023-04-27 09:14 UTC, lebeichuk commented on web_extention/analysisURLs.js
> +function getYouTubeChanelId(callback) {
тільки цей файл
я ж написав комент саме тут
до чого тут інші функції

2023-04-27 09:17 UTC, Vladyslav225 commented on web_extention/analysisURLs.js
> +function getYouTubeChanelId(callback) {
Добре, що я запитав
Я не правильно зрозумів

2023-04-27 09:54 UTC, lebeichuk approved these changes

2023-04-27 09:55 UTC, merged